<?php
/**
 * AddToConferenceTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\AddToConference;
use PHPUnit\Framework\TestCase;

/**
 * AddToConferenceTest Class Doc Comment
 *
 * @category    Class
 * @description The &#x60;AddToConference&#x60; command adds a Participant to a Conference. If this Participant currently is in another Conference, the Participant is first removed from that Conference. Two Call legs can be bridged together by creating a Conference and adding both Call legs to it via &#x60;AddToConference&#x60;.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddToConferenceTest extends TestCase
{
    protected $AddToConference;

    /**
     * Test "AddToConference"
     */
    public function setUp() : void
    {
        $this->AddToConference = new AddToConference();
    }
    /**
     * Test attribute "allow_call_control"
     */
    public function testPropertyAllowCallControl()
    {
        $this->AddToConference->setAllowCallControl(true);
        $this->assertEquals($this->AddToConference->getAllowCallControl(), true);
        $this->assertIsBool($this->AddToConference->getAllowCallControl());
    }
    /**
     * Test attribute "call_control_sequence"
     */
    public function testPropertyCallControlSequence()
    {
        $this->AddToConference->setCallControlSequence('TEST_STRING');
        $this->assertStringContainsString($this->AddToConference->getCallControlSequence(), 'TEST_STRING');
        $this->assertIsString($this->AddToConference->getCallControlSequence());
        

    }
    /**
     * Test attribute "call_control_url"
     */
    public function testPropertyCallControlUrl()
    {
        $this->AddToConference->setCallControlUrl('TEST_STRING');
        $this->assertStringContainsString($this->AddToConference->getCallControlUrl(), 'TEST_STRING');
        $this->assertIsString($this->AddToConference->getCallControlUrl());
        

    }
    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
        $this->AddToConference->setConferenceId('TEST_STRING');
        $this->assertStringContainsString($this->AddToConference->getConferenceId(), 'TEST_STRING');
        $this->assertIsString($this->AddToConference->getConferenceId());
        

    }
    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
        $this->AddToConference->setCallId(true);
        $this->assertEquals($this->AddToConference->getCallId(), true);
        $this->assertIsBool($this->AddToConference->getCallId());
    }
    /**
     * Test attribute "leave_conference_url"
     */
    public function testPropertyLeaveConferenceUrl()
    {
        $this->AddToConference->setLeaveConferenceUrl('TEST_STRING');
        $this->assertStringContainsString($this->AddToConference->getLeaveConferenceUrl(), 'TEST_STRING');
        $this->assertIsString($this->AddToConference->getLeaveConferenceUrl());
        

    }
    /**
     * Test attribute "listen"
     */
    public function testPropertyListen()
    {
        $this->AddToConference->setListen(true);
        $this->assertEquals($this->AddToConference->getListen(), true);
        $this->assertIsBool($this->AddToConference->getListen());
    }
    /**
     * Test attribute "notification_url"
     */
    public function testPropertyNotificationUrl()
    {
        $this->AddToConference->setNotificationUrl('TEST_STRING');
        $this->assertStringContainsString($this->AddToConference->getNotificationUrl(), 'TEST_STRING');
        $this->assertIsString($this->AddToConference->getNotificationUrl());
        

    }
    /**
     * Test attribute "start_conf_on_enter"
     */
    public function testPropertyStartConfOnEnter()
    {
        $this->AddToConference->setStartConfOnEnter(true);
        $this->assertEquals($this->AddToConference->getStartConfOnEnter(), true);
        $this->assertIsBool($this->AddToConference->getStartConfOnEnter());
    }
    /**
     * Test attribute "talk"
     */
    public function testPropertyTalk()
    {
        $this->AddToConference->setTalk(true);
        $this->assertEquals($this->AddToConference->getTalk(), true);
        $this->assertIsBool($this->AddToConference->getTalk());
    }
}
