<?php
/**
 * ApplicationResultAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FreeClimb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb;

use PHPUnit\Framework\TestCase;

/**
 * ApplicationResultAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description ApplicationResultAllOf
 * @package     FreeClimb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApplicationResultAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicationResultAllOf"
     */
    public function testApplicationResultAllOf()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "voice_url"
     */
    public function testPropertyVoiceUrl()
    {
    }

    /**
     * Test attribute "voice_fallback_url"
     */
    public function testPropertyVoiceFallbackUrl()
    {
    }

    /**
     * Test attribute "call_connect_url"
     */
    public function testPropertyCallConnectUrl()
    {
    }

    /**
     * Test attribute "status_callback_url"
     */
    public function testPropertyStatusCallbackUrl()
    {
    }

    /**
     * Test attribute "sms_url"
     */
    public function testPropertySmsUrl()
    {
    }

    /**
     * Test attribute "sms_fallback_url"
     */
    public function testPropertySmsFallbackUrl()
    {
    }
}
