<?php
/**
 * CallResultAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FreeClimb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb;

use PHPUnit\Framework\TestCase;

/**
 * CallResultAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description CallResultAllOf
 * @package     FreeClimb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CallResultAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CallResultAllOf"
     */
    public function testCallResultAllOf()
    {
    }

    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
    }

    /**
     * Test attribute "parent_call_id"
     */
    public function testPropertyParentCallId()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "phone_number_id"
     */
    public function testPropertyPhoneNumberId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "connect_time"
     */
    public function testPropertyConnectTime()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "connect_duration"
     */
    public function testPropertyConnectDuration()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "answered_by"
     */
    public function testPropertyAnsweredBy()
    {
    }

    /**
     * Test attribute "subresource_uris"
     */
    public function testPropertySubresourceUris()
    {
    }
}
