<?php
/**
 * ConferenceResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FreeClimb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb;

use PHPUnit\Framework\TestCase;

/**
 * ConferenceResultTest Class Doc Comment
 *
 * @category    Class
 * @description ConferenceResult
 * @package     FreeClimb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConferenceResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConferenceResult"
     */
    public function testConferenceResult()
    {
    }

    /**
     * Test attribute "uri"
     */
    public function testPropertyUri()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "date_updated"
     */
    public function testPropertyDateUpdated()
    {
    }

    /**
     * Test attribute "revision"
     */
    public function testPropertyRevision()
    {
    }

    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "play_beep"
     */
    public function testPropertyPlayBeep()
    {
    }

    /**
     * Test attribute "record"
     */
    public function testPropertyRecord()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "wait_url"
     */
    public function testPropertyWaitUrl()
    {
    }

    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
    }

    /**
     * Test attribute "status_callback_url"
     */
    public function testPropertyStatusCallbackUrl()
    {
    }

    /**
     * Test attribute "subresource_uris"
     */
    public function testPropertySubresourceUris()
    {
    }
}
