<?php
/**
 * ConferenceResultAllOfTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\ConferenceResultAllOf;
use PHPUnit\Framework\TestCase;

/**
 * ConferenceResultAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description ConferenceResultAllOf
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConferenceResultAllOfTest extends TestCase
{
    protected $ConferenceResultAllOf;

    /**
     * Test "ConferenceResultAllOf"
     */
    public function setUp() : void
    {
        $this->ConferenceResultAllOf = new ConferenceResultAllOf();
    }
    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
        $this->ConferenceResultAllOf->setConferenceId('TEST_STRING');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getConferenceId(), 'TEST_STRING');
        $this->assertIsString($this->ConferenceResultAllOf->getConferenceId());
        

    }
    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
        $this->ConferenceResultAllOf->setAccountId('TEST_STRING');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getAccountId(), 'TEST_STRING');
        $this->assertIsString($this->ConferenceResultAllOf->getAccountId());
        

    }
    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
        $this->ConferenceResultAllOf->setAlias('TEST_STRING');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getAlias(), 'TEST_STRING');
        $this->assertIsString($this->ConferenceResultAllOf->getAlias());
        

    }
    /**
     * Test attribute "play_beep"
     */
    public function testPropertyPlayBeep()
    {
        
        $this->ConferenceResultAllOf->setPlayBeep('always');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getPlayBeep(), 'always');
        $this->assertIsString($this->ConferenceResultAllOf->getPlayBeep());

    }
    /**
     * Test attribute "record"
     */
    public function testPropertyRecord()
    {
        $this->ConferenceResultAllOf->setRecord(true);
        $this->assertEquals($this->ConferenceResultAllOf->getRecord(), true);
        $this->assertIsBool($this->ConferenceResultAllOf->getRecord());
    }
    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        
        $this->ConferenceResultAllOf->setStatus('creating');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getStatus(), 'creating');
        $this->assertIsString($this->ConferenceResultAllOf->getStatus());

    }
    /**
     * Test attribute "wait_url"
     */
    public function testPropertyWaitUrl()
    {
        $this->ConferenceResultAllOf->setWaitUrl('TEST_STRING');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getWaitUrl(), 'TEST_STRING');
        $this->assertIsString($this->ConferenceResultAllOf->getWaitUrl());
        

    }
    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
        $this->ConferenceResultAllOf->setActionUrl('TEST_STRING');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getActionUrl(), 'TEST_STRING');
        $this->assertIsString($this->ConferenceResultAllOf->getActionUrl());
        

    }
    /**
     * Test attribute "status_callback_url"
     */
    public function testPropertyStatusCallbackUrl()
    {
        $this->ConferenceResultAllOf->setStatusCallbackUrl('TEST_STRING');
        $this->assertStringContainsString($this->ConferenceResultAllOf->getStatusCallbackUrl(), 'TEST_STRING');
        $this->assertIsString($this->ConferenceResultAllOf->getStatusCallbackUrl());
        

    }
    /**
     * Test attribute "subresource_uris"
     */
    public function testPropertySubresourceUris()
    {
        $this->ConferenceResultAllOf->setSubresourceUris(new \stdClass);
        $this->assertIsObject($this->ConferenceResultAllOf->getSubresourceUris());
    }
}
