<?php
/**
 * CreateConferenceTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\CreateConference;
use PHPUnit\Framework\TestCase;

/**
 * CreateConferenceTest Class Doc Comment
 *
 * @category    Class
 * @description The &#x60;CreateConference&#x60; command does exactly what its name implies — it creates an unpopulated Conference (one without any Participants). Once created, a Conference remains in FreeClimb until explicitly terminated by a customer. Once a Conference has been terminated, it can no longer be used.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateConferenceTest extends TestCase
{
    protected $CreateConference;

    /**
     * Test "CreateConference"
     */
    public function setUp() : void
    {
        $this->CreateConference = new CreateConference();
    }
    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
        $this->CreateConference->setActionUrl('TEST_STRING');
        $this->assertStringContainsString($this->CreateConference->getActionUrl(), 'TEST_STRING');
        $this->assertIsString($this->CreateConference->getActionUrl());
        

    }
    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
        $this->CreateConference->setAlias(true);
        $this->assertEquals($this->CreateConference->getAlias(), true);
        $this->assertIsBool($this->CreateConference->getAlias());
    }
    /**
     * Test attribute "play_beep"
     */
    public function testPropertyPlayBeep()
    {
        $this->CreateConference->setPlayBeep('TEST_STRING');
        $this->assertStringContainsString($this->CreateConference->getPlayBeep(), 'TEST_STRING');
        $this->assertIsString($this->CreateConference->getPlayBeep());
        

    }
    /**
     * Test attribute "record"
     */
    public function testPropertyRecord()
    {
        $this->CreateConference->setRecord(true);
        $this->assertEquals($this->CreateConference->getRecord(), true);
        $this->assertIsBool($this->CreateConference->getRecord());
    }
    /**
     * Test attribute "status_callback_url"
     */
    public function testPropertyStatusCallbackUrl()
    {
        $this->CreateConference->setStatusCallbackUrl(true);
        $this->assertEquals($this->CreateConference->getStatusCallbackUrl(), true);
        $this->assertIsBool($this->CreateConference->getStatusCallbackUrl());
    }
    /**
     * Test attribute "wait_url"
     */
    public function testPropertyWaitUrl()
    {
        $this->CreateConference->setWaitUrl('TEST_STRING');
        $this->assertStringContainsString($this->CreateConference->getWaitUrl(), 'TEST_STRING');
        $this->assertIsString($this->CreateConference->getWaitUrl());
        

    }
}
