<?php
/**
 * GetSpeechTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\GetSpeech;
use PHPUnit\Framework\TestCase;

/**
 * GetSpeechTest Class Doc Comment
 *
 * @category    Class
 * @description The &#x60;GetSpeech&#x60; command enables the Caller to respond to the application using a supported language. Unlike DTMF entry, which implicitly restricts the user to using the available buttons on the phone key pad, speech input allows for flexible audio inputs based on grammar. FreeClimb supports grammars written using GRXML compatible with the Microsoft Speech Platform. &#x60;GetSpeech&#x60; is only supported on a single call leg. It is not supported when there are two or more call legs connected (as in within a Conference).
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetSpeechTest extends TestCase
{
    protected $GetSpeech;

    /**
     * Test "GetSpeech"
     */
    public function setUp() : void
    {
        $this->GetSpeech = new GetSpeech();
    }
    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
        $this->GetSpeech->setActionUrl('TEST_STRING');
        $this->assertStringContainsString($this->GetSpeech->getActionUrl(), 'TEST_STRING');
        $this->assertIsString($this->GetSpeech->getActionUrl());
        

    }
    /**
     * Test attribute "grammar_type"
     */
    public function testPropertyGrammarType()
    {
        $this->GetSpeech->setGrammarType(12345);
        $this->assertEquals($this->GetSpeech->getGrammarType(), 12345);
        $this->assertIsInt($this->GetSpeech->getGrammarType());
    }
    /**
     * Test attribute "grammar_file"
     */
    public function testPropertyGrammarFile()
    {
        $this->GetSpeech->setGrammarFile('TEST_STRING');
        $this->assertStringContainsString($this->GetSpeech->getGrammarFile(), 'TEST_STRING');
        $this->assertIsString($this->GetSpeech->getGrammarFile());
        

    }
    /**
     * Test attribute "grammar_rule"
     */
    public function testPropertyGrammarRule()
    {
        $this->GetSpeech->setGrammarRule(true);
        $this->assertEquals($this->GetSpeech->getGrammarRule(), true);
        $this->assertIsBool($this->GetSpeech->getGrammarRule());
    }
    /**
     * Test attribute "play_beep"
     */
    public function testPropertyPlayBeep()
    {
        $this->GetSpeech->setPlayBeep('TEST_STRING');
        $this->assertStringContainsString($this->GetSpeech->getPlayBeep(), 'TEST_STRING');
        $this->assertIsString($this->GetSpeech->getPlayBeep());
        

    }
    /**
     * Test attribute "prompts"
     */
    public function testPropertyPrompts()
    {
        $this->GetSpeech->setPrompts(array());
        $this->assertIsArray($this->GetSpeech->getPrompts());
    }
    /**
     * Test attribute "no_input_timeout_ms"
     */
    public function testPropertyNoInputTimeoutMs()
    {
        $this->GetSpeech->setNoInputTimeoutMs(12345);
        $this->assertEquals($this->GetSpeech->getNoInputTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeech->getNoInputTimeoutMs());
    }
    /**
     * Test attribute "recognition_timeout_ms"
     */
    public function testPropertyRecognitionTimeoutMs()
    {
        $this->GetSpeech->setRecognitionTimeoutMs(12345);
        $this->assertEquals($this->GetSpeech->getRecognitionTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeech->getRecognitionTimeoutMs());
    }
    /**
     * Test attribute "confidence_threshold"
     */
    public function testPropertyConfidenceThreshold()
    {
        $this->GetSpeech->setConfidenceThreshold(12345);
        $this->assertEquals($this->GetSpeech->getConfidenceThreshold(), 12345);
        $this->assertIsNumeric($this->GetSpeech->getConfidenceThreshold());
    }
    /**
     * Test attribute "sensitivity_level"
     */
    public function testPropertySensitivityLevel()
    {
        $this->GetSpeech->setSensitivityLevel(12345);
        $this->assertEquals($this->GetSpeech->getSensitivityLevel(), 12345);
        $this->assertIsNumeric($this->GetSpeech->getSensitivityLevel());
    }
    /**
     * Test attribute "speech_complete_timeout_ms"
     */
    public function testPropertySpeechCompleteTimeoutMs()
    {
        $this->GetSpeech->setSpeechCompleteTimeoutMs(12345);
        $this->assertEquals($this->GetSpeech->getSpeechCompleteTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeech->getSpeechCompleteTimeoutMs());
    }
    /**
     * Test attribute "speech_incomplete_timeout_ms"
     */
    public function testPropertySpeechIncompleteTimeoutMs()
    {
        $this->GetSpeech->setSpeechIncompleteTimeoutMs(12345);
        $this->assertEquals($this->GetSpeech->getSpeechIncompleteTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeech->getSpeechIncompleteTimeoutMs());
    }
    /**
     * Test attribute "privacy_mode"
     */
    public function testPropertyPrivacyMode()
    {
        $this->GetSpeech->setPrivacyMode(true);
        $this->assertEquals($this->GetSpeech->getPrivacyMode(), true);
        $this->assertIsBool($this->GetSpeech->getPrivacyMode());
    }
}
