<?php
/**
 * GetSpeechAllOfTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\GetSpeechAllOf;
use PHPUnit\Framework\TestCase;

/**
 * GetSpeechAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description GetSpeechAllOf
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetSpeechAllOfTest extends TestCase
{
    protected $GetSpeechAllOf;

    /**
     * Test "GetSpeechAllOf"
     */
    public function setUp() : void
    {
        $this->GetSpeechAllOf = new GetSpeechAllOf();
    }
    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
        $this->GetSpeechAllOf->setActionUrl('TEST_STRING');
        $this->assertStringContainsString($this->GetSpeechAllOf->getActionUrl(), 'TEST_STRING');
        $this->assertIsString($this->GetSpeechAllOf->getActionUrl());
        

    }
    /**
     * Test attribute "grammar_type"
     */
    public function testPropertyGrammarType()
    {
        $this->GetSpeechAllOf->setGrammarType(12345);
        $this->assertEquals($this->GetSpeechAllOf->getGrammarType(), 12345);
        $this->assertIsInt($this->GetSpeechAllOf->getGrammarType());
    }
    /**
     * Test attribute "grammar_file"
     */
    public function testPropertyGrammarFile()
    {
        $this->GetSpeechAllOf->setGrammarFile('TEST_STRING');
        $this->assertStringContainsString($this->GetSpeechAllOf->getGrammarFile(), 'TEST_STRING');
        $this->assertIsString($this->GetSpeechAllOf->getGrammarFile());
        

    }
    /**
     * Test attribute "grammar_rule"
     */
    public function testPropertyGrammarRule()
    {
        $this->GetSpeechAllOf->setGrammarRule(true);
        $this->assertEquals($this->GetSpeechAllOf->getGrammarRule(), true);
        $this->assertIsBool($this->GetSpeechAllOf->getGrammarRule());
    }
    /**
     * Test attribute "play_beep"
     */
    public function testPropertyPlayBeep()
    {
        $this->GetSpeechAllOf->setPlayBeep('TEST_STRING');
        $this->assertStringContainsString($this->GetSpeechAllOf->getPlayBeep(), 'TEST_STRING');
        $this->assertIsString($this->GetSpeechAllOf->getPlayBeep());
        

    }
    /**
     * Test attribute "prompts"
     */
    public function testPropertyPrompts()
    {
        $this->GetSpeechAllOf->setPrompts(array());
        $this->assertIsArray($this->GetSpeechAllOf->getPrompts());
    }
    /**
     * Test attribute "no_input_timeout_ms"
     */
    public function testPropertyNoInputTimeoutMs()
    {
        $this->GetSpeechAllOf->setNoInputTimeoutMs(12345);
        $this->assertEquals($this->GetSpeechAllOf->getNoInputTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeechAllOf->getNoInputTimeoutMs());
    }
    /**
     * Test attribute "recognition_timeout_ms"
     */
    public function testPropertyRecognitionTimeoutMs()
    {
        $this->GetSpeechAllOf->setRecognitionTimeoutMs(12345);
        $this->assertEquals($this->GetSpeechAllOf->getRecognitionTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeechAllOf->getRecognitionTimeoutMs());
    }
    /**
     * Test attribute "confidence_threshold"
     */
    public function testPropertyConfidenceThreshold()
    {
        $this->GetSpeechAllOf->setConfidenceThreshold(12345);
        $this->assertEquals($this->GetSpeechAllOf->getConfidenceThreshold(), 12345);
        $this->assertIsNumeric($this->GetSpeechAllOf->getConfidenceThreshold());
    }
    /**
     * Test attribute "sensitivity_level"
     */
    public function testPropertySensitivityLevel()
    {
        $this->GetSpeechAllOf->setSensitivityLevel(12345);
        $this->assertEquals($this->GetSpeechAllOf->getSensitivityLevel(), 12345);
        $this->assertIsNumeric($this->GetSpeechAllOf->getSensitivityLevel());
    }
    /**
     * Test attribute "speech_complete_timeout_ms"
     */
    public function testPropertySpeechCompleteTimeoutMs()
    {
        $this->GetSpeechAllOf->setSpeechCompleteTimeoutMs(12345);
        $this->assertEquals($this->GetSpeechAllOf->getSpeechCompleteTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeechAllOf->getSpeechCompleteTimeoutMs());
    }
    /**
     * Test attribute "speech_incomplete_timeout_ms"
     */
    public function testPropertySpeechIncompleteTimeoutMs()
    {
        $this->GetSpeechAllOf->setSpeechIncompleteTimeoutMs(12345);
        $this->assertEquals($this->GetSpeechAllOf->getSpeechIncompleteTimeoutMs(), 12345);
        $this->assertIsInt($this->GetSpeechAllOf->getSpeechIncompleteTimeoutMs());
    }
    /**
     * Test attribute "privacy_mode"
     */
    public function testPropertyPrivacyMode()
    {
        $this->GetSpeechAllOf->setPrivacyMode(true);
        $this->assertEquals($this->GetSpeechAllOf->getPrivacyMode(), true);
        $this->assertIsBool($this->GetSpeechAllOf->getPrivacyMode());
    }
}
