<?php
/**
 * GetSpeechAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FreeClimb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb;

use PHPUnit\Framework\TestCase;

/**
 * GetSpeechAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description GetSpeechAllOf
 * @package     FreeClimb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetSpeechAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetSpeechAllOf"
     */
    public function testGetSpeechAllOf()
    {
    }

    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
    }

    /**
     * Test attribute "grammar_type"
     */
    public function testPropertyGrammarType()
    {
    }

    /**
     * Test attribute "grammar_file"
     */
    public function testPropertyGrammarFile()
    {
    }

    /**
     * Test attribute "grammar_rule"
     */
    public function testPropertyGrammarRule()
    {
    }

    /**
     * Test attribute "play_beep"
     */
    public function testPropertyPlayBeep()
    {
    }

    /**
     * Test attribute "prompts"
     */
    public function testPropertyPrompts()
    {
    }

    /**
     * Test attribute "no_input_timeout_ms"
     */
    public function testPropertyNoInputTimeoutMs()
    {
    }

    /**
     * Test attribute "recognition_timeout_ms"
     */
    public function testPropertyRecognitionTimeoutMs()
    {
    }

    /**
     * Test attribute "confidence_threshold"
     */
    public function testPropertyConfidenceThreshold()
    {
    }

    /**
     * Test attribute "sensitivity_level"
     */
    public function testPropertySensitivityLevel()
    {
    }

    /**
     * Test attribute "speech_complete_timeout_ms"
     */
    public function testPropertySpeechCompleteTimeoutMs()
    {
    }

    /**
     * Test attribute "speech_incomplete_timeout_ms"
     */
    public function testPropertySpeechIncompleteTimeoutMs()
    {
    }

    /**
     * Test attribute "privacy_mode"
     */
    public function testPropertyPrivacyMode()
    {
    }
}
