<?php
/**
 * MakeCallRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FreeClimb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb;

use PHPUnit\Framework\TestCase;

/**
 * MakeCallRequestTest Class Doc Comment
 *
 * @category    Class
 * @description MakeCallRequest
 * @package     FreeClimb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MakeCallRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MakeCallRequest"
     */
    public function testMakeCallRequest()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {
    }

    /**
     * Test attribute "send_digits"
     */
    public function testPropertySendDigits()
    {
    }

    /**
     * Test attribute "if_machine"
     */
    public function testPropertyIfMachine()
    {
    }

    /**
     * Test attribute "if_machine_url"
     */
    public function testPropertyIfMachineUrl()
    {
    }

    /**
     * Test attribute "timeout"
     */
    public function testPropertyTimeout()
    {
    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "parent_call_id"
     */
    public function testPropertyParentCallId()
    {
    }
}
