<?php
/**
 * OutDialTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FreeClimb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb;

use PHPUnit\Framework\TestCase;

/**
 * OutDialTest Class Doc Comment
 *
 * @category    Class
 * @description OutDial
 * @package     FreeClimb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OutDialTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OutDial"
     */
    public function testOutDial()
    {
    }

    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
    }

    /**
     * Test attribute "call_connect_url"
     */
    public function testPropertyCallConnectUrl()
    {
    }

    /**
     * Test attribute "calling_number"
     */
    public function testPropertyCallingNumber()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "if_machine"
     */
    public function testPropertyIfMachine()
    {
    }

    /**
     * Test attribute "send_digits"
     */
    public function testPropertySendDigits()
    {
    }

    /**
     * Test attribute "status_callback_url"
     */
    public function testPropertyStatusCallbackUrl()
    {
    }

    /**
     * Test attribute "timeout"
     */
    public function testPropertyTimeout()
    {
    }
}
