<?php
/**
 * RemoveFromConferenceTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\RemoveFromConference;
use PHPUnit\Framework\TestCase;

/**
 * RemoveFromConferenceTest Class Doc Comment
 *
 * @category    Class
 * @description The &#x60;RemoveFromConference&#x60; command removes a Participant from a Conference but does not hang up. Instead, the Call is simply unbridged and what happens next with the Call is determined by the PerCL returned in response to the &#x60;leaveConferenceUrl&#x60; attribute.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RemoveFromConferenceTest extends TestCase
{
    protected $RemoveFromConference;

    /**
     * Test "RemoveFromConference"
     */
    public function setUp() : void
    {
        $this->RemoveFromConference = new RemoveFromConference();
    }
    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
        $this->RemoveFromConference->setCallId('TEST_STRING');
        $this->assertStringContainsString($this->RemoveFromConference->getCallId(), 'TEST_STRING');
        $this->assertIsString($this->RemoveFromConference->getCallId());
        

    }
}
