<?php
/**
 * SetListenTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\SetListen;
use PHPUnit\Framework\TestCase;

/**
 * SetListenTest Class Doc Comment
 *
 * @category    Class
 * @description The &#x60;SetListen&#x60; command enables or disables the listen privilege for a Conference Participant provided both calls are in the same conference. The Participant can hear what the other participants are saying only if this privilege is enabled.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SetListenTest extends TestCase
{
    protected $SetListen;

    /**
     * Test "SetListen"
     */
    public function setUp() : void
    {
        $this->SetListen = new SetListen();
    }
    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
        $this->SetListen->setCallId('TEST_STRING');
        $this->assertStringContainsString($this->SetListen->getCallId(), 'TEST_STRING');
        $this->assertIsString($this->SetListen->getCallId());
        

    }
    /**
     * Test attribute "listen"
     */
    public function testPropertyListen()
    {
        $this->SetListen->setListen(true);
        $this->assertEquals($this->SetListen->getListen(), true);
        $this->assertIsBool($this->SetListen->getListen());
    }
}
