<?php
/**
 * DefaultApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FreeClimb\Api\Test\Api;

use \FreeClimb\Api\Configuration;
use \FreeClimb\Api\ApiException;
use \FreeClimb\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for buyAPhoneNumber
     *
     * Buy a Phone Number.
     *
     */
    public function testBuyAPhoneNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAConference
     *
     * Create a Conference.
     *
     */
    public function testCreateAConference()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAQueue
     *
     * Create a Queue.
     *
     */
    public function testCreateAQueue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAnApplication
     *
     * Create an application.
     *
     */
    public function testCreateAnApplication()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteARecording
     *
     * Delete a Recording.
     *
     */
    public function testDeleteARecording()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAnApplication
     *
     * Delete an application.
     *
     */
    public function testDeleteAnApplication()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAnIncomingNumber
     *
     * Delete an Incoming Number.
     *
     */
    public function testDeleteAnIncomingNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dequeueAMember
     *
     * Dequeue a Member.
     *
     */
    public function testDequeueAMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dequeueHeadMember
     *
     * Dequeue Head Member.
     *
     */
    public function testDequeueHeadMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadARecordingFile
     *
     * Download a Recording File.
     *
     */
    public function testDownloadARecordingFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for filterLogs
     *
     * Filter Logs.
     *
     */
    public function testFilterLogs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getACall
     *
     * Get a Call.
     *
     */
    public function testGetACall()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAConference
     *
     * Get a Conference.
     *
     */
    public function testGetAConference()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAMember
     *
     * Get a Member.
     *
     */
    public function testGetAMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAParticipant
     *
     * Get a Participant.
     *
     */
    public function testGetAParticipant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAQueue
     *
     * Get a Queue.
     *
     */
    public function testGetAQueue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getARecording
     *
     * Get a Recording.
     *
     */
    public function testGetARecording()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAnAccount
     *
     * Get an Account.
     *
     */
    public function testGetAnAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAnApplication
     *
     * Get an Application.
     *
     */
    public function testGetAnApplication()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAnIncomingNumber
     *
     * Get an Incoming Number.
     *
     */
    public function testGetAnIncomingNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAnSmsMessage
     *
     * Get an SMS Message.
     *
     */
    public function testGetAnSmsMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getHeadMember
     *
     * Get Head Member.
     *
     */
    public function testGetHeadMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listActiveQueues
     *
     * List Active Queues.
     *
     */
    public function testListActiveQueues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAllAccountLogs
     *
     * List All Account Logs.
     *
     */
    public function testListAllAccountLogs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAnApplication
     *
     * List applications.
     *
     */
    public function testListAnApplication()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAvailableNumbers
     *
     * List available numbers.
     *
     */
    public function testListAvailableNumbers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCallLogs
     *
     * List Call Logs.
     *
     */
    public function testListCallLogs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCallRecordings
     *
     * List Call Recordings.
     *
     */
    public function testListCallRecordings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCalls
     *
     * List Calls.
     *
     */
    public function testListCalls()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listConferences
     *
     * List Conferences.
     *
     */
    public function testListConferences()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listIncomingNumbers
     *
     * List Incoming Numbers.
     *
     */
    public function testListIncomingNumbers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMembers
     *
     * List Members.
     *
     */
    public function testListMembers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listParticipants
     *
     * List Participants.
     *
     */
    public function testListParticipants()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRecordings
     *
     * List Recordings.
     *
     */
    public function testListRecordings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsMessages
     *
     * List SMS Messages.
     *
     */
    public function testListSmsMessages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for makeACall
     *
     * Make a Call.
     *
     */
    public function testMakeACall()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeAParticipant
     *
     * Remove a Participant.
     *
     */
    public function testRemoveAParticipant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendAnSmsMessage
     *
     * Send an SMS Message.
     *
     */
    public function testSendAnSmsMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for streamARecordingFile
     *
     * Stream a Recording File.
     *
     */
    public function testStreamARecordingFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAConference
     *
     * Update a Conference.
     *
     */
    public function testUpdateAConference()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateALiveCall
     *
     * Update a Live Call.
     *
     */
    public function testUpdateALiveCall()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAParticipant
     *
     * Update a Participant.
     *
     */
    public function testUpdateAParticipant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAQueue
     *
     * Update a Queue.
     *
     */
    public function testUpdateAQueue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAnAccount
     *
     * Manage an account.
     *
     */
    public function testUpdateAnAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAnApplication
     *
     * Update an application.
     *
     */
    public function testUpdateAnApplication()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAnIncomingNumber
     *
     * Update an Incoming Number.
     *
     */
    public function testUpdateAnIncomingNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
